# -*- coding: utf-8 -*-
"""Proyecto programación- Equipo 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C6E2Dd3u2N2XMu5XNNS4_6UzthRyFEGr
"""

# Commented out IPython magic to ensure Python compatibility.
#Universidad de Colima- Facultad de Ingeniería Civil
#Carrera: Ingeniero Topógrafo Geomático
#Elaborado por: Avalos Rocha Andrea, Jiménez Vargas Mariel del Rosario y Uribe García Leonardo Miguel
#Grado y grupo: 3°B
#Programación de computadoras II

# %matplotlib inline
from google.colab import drive
from google.colab import data_table
from vega_datasets import data
import pandas as pd
import numpy as np
import xlrd
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
import seaborn as sb
from mpl_toolkits.basemap.test import Basemap
from geopy.geocoders import Nominatim
import time
import math

print('--Programa que calcula el desnivel entre dos puntos referidos a una superficie--')
print('Bienvenido a nuestro programa, este te ayudará a conocer el desnivel de una nivelación topográfica y te mostrára de forma gráfica como es esta')
print('IMPORTANTE: Para que el programa te funcione debes tener tu información en Excel separada con columnas y cada columna con los nombres: P.V, Lect(+),  (A.I), Lect(-) y Cotas')
print('P.V significa Punto Visado')
print('A.I significa Altura del instrumento')

data_table.enable_dataframe_formatter()
data.airports()
drive.mount('/gdrive')
df= pd.read_excel('/gdrive/MyDrive/Colab Notebooks/Proyecto_Integrador/Nivelación.xlsx', sheet_name = "Hoja2")
print(df.head())

columna_lectpostivas = df['Lect(+)']
sumlecturaspositivas= sum(columna_lectpostivas)
print('La suma de las lecturas positivas es: ', sumlecturaspositivas)

columna_lectnegativas = df['Lect(-)']
sumlecturasnegativas= sum(columna_lectnegativas)
print('La suma de las lecturas negativas es: ', sumlecturasnegativas)

desnivel= sumlecturaspositivas-sumlecturasnegativas
print('El desnivel de esta nivelación es: ', desnivel)


valores= df[['P.V','Cota']]
ax= valores.plot(x='P.V',y='Cota',rot= 0)
plt.xlabel("P.V")
plt.ylabel("Cota")
plt.title("Nivelación Geométrica- Perfil del tramo")
plt.show()

if desnivel > 0:
  print('La pendiente va de forma creciente')
if desnivel < 0:
  print('La pendiente va de forma decreciente')
if desnivel == 0:
  print('No hay pendiente, el terreno es plano')

geolocator = Nominatim(user_agent="AppMap")
lugar= input("Lugar donde se hizo la nivelación: ")
location = geolocator.geocode(lugar)
print(location)
print((location.latitude, location.longitude))
geo = Nominatim(user_agent="AppMap", timeout=2)
zona = geo.geocode(lugar)
plt.figure(figsize=(16,12))
my_map=Basemap(projection="robin", lon_0=0,lat_0=0)
my_map.drawcoastlines()
my_map.drawcountries()
my_map.fillcontinents(color='green')
x,y = my_map(zona.longitude,zona.latitude)
my_map.plot(x,y,color='red', marker="o",markersize="15")
plt.title("Ubicación donde se hizo la nivelación")

!pip install Basemap